# Generated by Django 4.2.10 on 2024-04-18 08:53

import apps.common.image
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('ssn', models.CharField(blank=True, max_length=255, null=True, verbose_name='SSN')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zip')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Phone')),
                ('second_driver', models.BooleanField(default=False, verbose_name='Second Driver (team)')),
                ('lisense_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lisense Number')),
                ('lisense_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lisense State')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ('-id',),
            },
            bases=(models.Model, apps.common.image.ImageService),
        ),
    ]
