# Generated by Django 4.2.10 on 2024-02-22 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
