# Generated by Django 4.2.10 on 2024-03-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_remove_driver_is_staff_alter_driver_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_type',
        ),
    ]
