# Generated by Django 4.2.10 on 2024-05-29 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_id', models.CharField(max_length=255)),
                ('transport_type', models.CharField(choices=[('CARGO VAN', 'CARGO VAN'), ('SPRINTER VAN', 'SPRINTER_VAN'), ('VAN', 'VAN'), ('SPRINTER', 'SPRINTER'), ('BOX TRUCK', 'BOX TRUCK'), ('SMALL STRAIGHT', 'SMALL STRAIGHT'), ('LARGE STRAIGHT', 'LARGE STRAIGHT'), ('LIFTGATE', 'LIFTGATE'), ('FLATBED', 'FLATBED'), ('TRACTOR', 'TRACTOR'), ('REEFER', 'REEFER')], default='SPRINTER VAN', max_length=255)),
                ('vehicle_model', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_year', models.CharField(blank=True, max_length=4, null=True)),
                ('width', models.SmallIntegerField(blank=True, null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('length', models.SmallIntegerField(blank=True, null=True)),
                ('payload', models.SmallIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=255, null=True)),
                ('lisense_plate', models.CharField(blank=True, max_length=255, null=True)),
                ('lisense_state', models.CharField(blank=True, max_length=255, null=True)),
                ('lisense_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('insurance_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_latitude', models.FloatField(blank=True, null=True)),
                ('location_longitude', models.FloatField(blank=True, null=True)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatchers', to=settings.AUTH_USER_MODEL)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='driver.driver')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
