# Generated by Django 4.2.10 on 2024-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
