# Generated by Django 4.2.10 on 2024-05-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="location_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="location_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
