# Generated by Django 4.2.10 on 2024-04-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_vehicles_height_alter_vehicles_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='dock_high',
            field=models.BooleanField(default=False),
        ),
    ]
