# Generated by Django 4.2.10 on 2024-04-18 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0004_remove_driver_avatar_remove_driver_is_verified_and_more'),
        ('vehicle', '0003_vehicles_dock_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='dispatcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatcher_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicles', to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
