# Generated by Django 4.2.10 on 2024-04-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_vehicles_coordinate_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='dock_high',
            field=models.CharField(default='No', max_length=255),
        ),
    ]
