# Generated by Django 4.2.10 on 2024-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_vehicles_dock_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='coordinate_from',
            field=models.CharField(default='40.730610,-73.935242', max_length=255),
        ),
    ]
