# Generated by Django 4.2.10 on 2024-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
