# Generated by Django 4.2.5 on 2023-11-29 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_rename_location_user_lat_user_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='distance_from_pickup',
        ),
    ]
