# Generated by Django 4.2.5 on 2024-01-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_distance_from_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicle_type',
        ),
    ]
