# Generated by Django 4.2.5 on 2024-01-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('dims', models.CharField(blank=True, max_length=255, null=True)),
                ('mc', models.CharField(blank=True, max_length=255, null=True)),
                ('miles', models.FloatField(blank=True, null=True)),
                ('eta_to_pick_up', models.CharField(blank=True, max_length=255, null=True)),
                ('dock_high', models.BooleanField(blank=True, null=True)),
                ('account', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
