# Generated by Django 4.2.10 on 2024-04-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='order.order'),
        ),
    ]
