# Generated by Django 4.2.5 on 2024-01-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='account',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='dims',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='dock_high',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='eta_to_pick_up',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='mc',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='rate',
        ),
        migrations.AddField(
            model_name='letter',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
