# Generated by Django 4.2.10 on 2024-05-02 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0003_letter_broker_price_letter_driver_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='dispatcher_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='broker_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='letter',
            name='driver_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
