# Generated by Django 4.2.10 on 2024-02-22 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_delete_email_remove_letter_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='letter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
