# Generated by Django 4.2.10 on 2024-02-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_remove_driver_is_staff_alter_driver_avatar_and_more'),
        ('order', '0013_alter_order_options_remove_order_created_and_more'),
        ('letter', '0004_letter_created_at_letter_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='driver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
        migrations.AddField(
            model_name='letter',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
