# Generated by Django 4.2.10 on 2024-05-02 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0004_letter_dispatcher_id_alter_letter_broker_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='dispatcher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
