# Generated by Django 4.2.10 on 2024-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_alter_letter_dispatcher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='broker_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='letter',
            name='driver_price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
    ]
