# Generated by Django 4.2.10 on 2024-02-24 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_remove_driver_is_staff_alter_driver_avatar_and_more'),
        ('order', '0013_alter_order_options_remove_order_created_and_more'),
        ('letter', '0005_letter_driver_id_letter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='driver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='order.order'),
        ),
    ]
