# Generated by Django 4.2.10 on 2024-05-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0006_alter_letter_broker_price_alter_letter_driver_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='broker_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='letter',
            name='driver_price',
            field=models.IntegerField(default=1),
        ),
    ]
