# Generated by Django 4.2.10 on 2024-03-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_remove_driver_is_staff_alter_driver_avatar_and_more'),
        ('order', '0021_alter_order_order_status'),
        ('letter', '0006_alter_letter_driver_id_alter_letter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter', to='order.order'),
        ),
    ]
