# Generated by Django 4.2.10 on 2024-05-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0007_alter_letter_broker_price_alter_letter_driver_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='comment',
            field=models.TextField(default='Empty'),
        ),
    ]
