# Generated by Django 4.2.10 on 2024-05-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_alter_letter_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='comment',
            field=models.TextField(),
        ),
    ]
