# Generated by Django 4.2.10 on 2024-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0009_alter_letter_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='broker_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='letter',
            name='driver_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
