# Generated by Django 4.2.5 on 2023-12-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_email', '0005_order_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_info',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
