# Generated by Django 4.2.5 on 2023-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_email', '0007_alter_order_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
