# Generated by Django 4.2.5 on 2023-12-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_email', '0008_alter_order_contact_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contact_info',
            new_name='company_address',
        ),
        migrations.AddField(
            model_name='order',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
