# Generated by Django 4.2.10 on 2024-04-18 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker_company', models.CharField(max_length=255)),
                ('rate_confirmation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('order_status', models.CharField(choices=[('DEFAULT', '----'), ('PENDING', 'Pending'), ('MY_LOADS', 'My Loads')], default='DEFAULT', max_length=100)),
                ('my_loads_status', models.IntegerField(choices=[(0, 'Active'), (1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Checkout'), (7, 'Completed')], default=0)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_up_at', models.CharField(blank=True, max_length=255, null=True)),
                ('pick_up_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('deliver_to', models.CharField(blank=True, max_length=255, null=True)),
                ('deliver_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('line', models.CharField(blank=True, max_length=255, null=True)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('broker_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('posted', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('expires', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dock_level', models.CharField(blank=True, max_length=255, null=True)),
                ('hazmat', models.CharField(blank=True, max_length=255, null=True)),
                ('fast_load', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=400, null=True)),
                ('load_type', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_required', models.CharField(blank=True, max_length=255, null=True)),
                ('pieces', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('stackable', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='orders/logos/')),
            ],
        ),
    ]
