# Generated by Django 4.2.10 on 2024-06-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='expires',
            new_name='expires_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='posted',
            new_name='posted_date',
        ),
    ]
