# Generated by Django 4.2.10 on 2024-05-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='match',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
