# Generated by Django 4.2.10 on 2024-06-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
