# Generated by Django 4.2.10 on 2024-05-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_order_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='match',
            field=models.CharField(default=0),
        ),
    ]
