# Generated by Django 4.2.10 on 2024-05-28 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_delivery_latitude_order_delivery_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="expires",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="posted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
