# Generated by Django 4.2.10 on 2024-04-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_coordinate_from_order_coordinate_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coordinate_from',
            field=models.CharField(default='40.730610, -73.935242', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='coordinate_to',
            field=models.CharField(default='40.650002, -73.949997', max_length=255),
        ),
    ]
