# Generated by Django 4.2.10 on 2024-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='match',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
