# Generated by Django 4.2.10 on 2024-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='broker_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='driver_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
