# Generated by Django 4.2.10 on 2024-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_coordinate_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coordinate_from',
            field=models.CharField(default='40.730610,-73.935242', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='coordinate_to',
            field=models.CharField(default='40.650002,-73.949997', max_length=255),
        ),
    ]
