# Generated by Django 4.2.5 on 2023-12-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0004_alter_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
