# Generated by Django 4.2.10 on 2024-04-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_coordinate_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='match',
            field=models.IntegerField(default=0),
        ),
    ]
