# Generated by Django 4.2.10 on 2024-05-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AWAITING_BID', 'AWAITING BID'), ('EXPIRED', 'EXPIRED'), ('REFUSED', 'REFUSED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('CONFIRMED', 'CONFIRMED')], default='PENDING', max_length=100),
        ),
    ]
