# Generated by Django 4.2.10 on 2024-05-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_is_active_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='my_loads_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AWAITING_BID', 'AWAITING BID'), ('REFUSED', 'REFUSED'), ('ASSIGN', 'ASSIGN'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=100),
        ),
        migrations.CreateModel(
            name='MyLoadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.IntegerField(choices=[(0, 'NULL'), (1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered')], default=0)),
                ('current_status', models.IntegerField(choices=[(0, 'NULL'), (1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered')], default=0)),
                ('next_status', models.IntegerField(choices=[(0, 'NULL'), (1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered')], default=0)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_load_status', to='order.order')),
            ],
        ),
    ]
