# Generated by Django 4.2.10 on 2024-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_my_loads_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transit_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transit_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myloadstatus',
            name='current_status',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='myloadstatus',
            name='next_status',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='myloadstatus',
            name='previous_status',
            field=models.IntegerField(choices=[(0, 'NULL'), (1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AWAITING_BID', 'AWAITING BID'), ('REFUSED', 'REFUSED'), ('ASSIGN', 'ASSIGN'), ('CHECKOUT', 'CHECKOUT'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=100),
        ),
    ]
