# Generated by Django 4.2.10 on 2024-05-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myloadstatus',
            name='current_status',
            field=models.IntegerField(choices=[(1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='myloadstatus',
            name='next_status',
            field=models.IntegerField(choices=[(1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='myloadstatus',
            name='previous_status',
            field=models.IntegerField(choices=[(1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('AWAITING_BID', 'AWAITING BID'), ('REFUSED', 'REFUSED'), ('ACTIVE', 'ACTIVE'), ('CHECKOUT', 'CHECKOUT'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=100),
        ),
    ]
