# Generated by Django 4.2.10 on 2024-05-19 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_myloadstatus_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myloadstatus',
            name='location_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
