# Generated by Django 4.2.10 on 2024-05-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_myloadstatus_location_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myloadstatus',
            name='location_updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='coordinate_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='coordinate_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
