# Generated by Django 4.2.10 on 2024-05-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_myloadstatus_location_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myloadstatus',
            name='current_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='myloadstatus',
            name='next_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='myloadstatus',
            name='previous_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Paid off'), (7, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='match',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='transit_distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transit_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
