# Generated by Django 4.2.10 on 2024-02-24 10:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_deliver_date_cen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_date_CEN',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 24, 11, 17, 51, 24208, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date_EST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 24, 11, 17, 51, 24272, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_date_CEN',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_up_date_EST',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='this_posting_expires_cen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 24, 10, 27, 51, 24545, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='this_posting_expires_est',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 24, 10, 27, 51, 24582, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
