# Generated by Django 4.2.10 on 2024-02-29 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_deliver_date_cen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='orders/logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date_CEN',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 29, 7, 33, 30, 57750, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date_EST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 29, 7, 33, 30, 57770, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DEFAULT', '----'), ('PENDING', 'Pending'), ('MY_LOADS', 'My Loads'), ('A', 'Выехал на точку А'), ('B', 'Загрузил'), ('C', 'В дороге'), ('D', 'Выгрузил')], default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='this_posting_expires_cen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 29, 6, 43, 30, 57850, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='this_posting_expires_est',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 29, 6, 43, 30, 57861, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
