# Generated by Django 4.2.10 on 2024-03-04 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_template_alter_order_deliver_date_cen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_date_CEN',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 4, 36, 12, 478092, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date_EST',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 4, 36, 12, 478110, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='this_posting_expires_cen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 3, 46, 12, 478267, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='this_posting_expires_est',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 4, 3, 46, 12, 478280, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
