# Generated by Django 4.2.10 on 2024-03-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_deliver_date_cen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='my_loads_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'I am going to the load'), (2, 'Uploaded'), (3, 'On the way'), (4, 'Unloaded'), (5, 'Delivered'), (6, 'Checkout')], default=0),
        ),
    ]
