# Generated by Django 4.2.10 on 2024-03-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_my_loads_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DEFAULT', '----'), ('PENDING', 'Pending'), ('MY_LOADS', 'My Loads')], default='DEFAULT', max_length=100),
        ),
    ]
