# Generated by Django 4.2.10 on 2024-03-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assign', to='order.order'),
        ),
    ]
