# Generated by Django 4.2.10 on 2024-04-08 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_assign_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='broker_phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliver_date_CEN',
            new_name='deliver_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dims',
            new_name='dimensions',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='from_whom',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliver_date_EST',
            new_name='expires',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hazardous',
        ),
        migrations.RemoveField(
            model_name='order',
            name='load_posted_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pick_up_date_CEN',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pick_up_date_EST',
        ),
        migrations.RemoveField(
            model_name='order',
            name='suggested_truck_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='this_posting_expires_cen',
        ),
        migrations.RemoveField(
            model_name='order',
            name='this_posting_expires_est',
        ),
        migrations.AddField(
            model_name='order',
            name='broker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hazmat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='load_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pick_up_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pieces',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
